Adicionar O meu nome
omarcostahamido/IntroToGithub pull request #8
Opened 2024-02-29 15:47 UTC by gratinad

Chamo me frederico e fiz as tarefas

2024-02-29 21:48 UTC, omarcostahamido requested changes
olá @gratinad 
conseguiste criar um pull request! muito bem 😄 
mas este desafio final ainda não está completo.
por favor vê os meus comentários/revisão em seguida.

2024-02-29 21:48 UTC, omarcostahamido commented on hall-of-fame.md
> +
- não há necessidade de inserir esta linha mais aqui.
- favor deixar linhas 3 e 4 tal e qual como estavam

2024-02-29 21:48 UTC, omarcostahamido commented on hall-of-fame.md
> +Frederico Leitão
- ok, inseriste algo - um teste -, e conseguiste criar um PR válido! muito bem.
- mas agora vem o verdadeiro desafio: como fazer um quadrado com a tua imagem de perfil de utilizador do github e linkar isso à página do teu perfil?
- _hint:_ vê o que eu fiz na linha 4 😉

2024-03-05 14:43 UTC, gratinad commented
Vou então fechar este PR.
Obrigado.

2024-03-05 14:43 UTC, closed without merging